config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations]
  devise_for :users
  resources :adresses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "admin" => "admin#index"
  
  # Defines the root path route ("/")
  root "adresses#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/adress.rb
class Adress < ApplicationRecord
    has_one_attached :image do |attachable|
        attachable.variant :thumb, resize_to_limit: [100,100]
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :authenticate_admin!
    
    def index
    end
end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController
  before_action :set_adress, only: %i[ show edit update destroy ]

  # GET /adresses or /adresses.json
  def index
    @adresses = Adress.all
  end

  # GET /adresses/1 or /adresses/1.json
  def show
  end

  # GET /adresses/new
  def new
    @adress = Adress.new
  end

  # GET /adresses/1/edit
  def edit
  end

  # POST /adresses or /adresses.json
  def create
    @adress = Adress.new(adress_params)

    respond_to do |format|
      if @adress.save
        format.html { redirect_to adress_url(@adress), notice: "Adress was successfully created." }
        format.json { render :show, status: :created, location: @adress }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adresses/1 or /adresses/1.json
  def update
    respond_to do |format|
      if @adress.update(adress_params)
        format.html { redirect_to adress_url(@adress), notice: "Adress was successfully updated." }
        format.json { render :show, status: :ok, location: @adress }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adresses/1 or /adresses/1.json
  def destroy
    @adress.destroy!

    respond_to do |format|
      format.html { redirect_to adresses_url, notice: "Adress was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adress
      @adress = Adress.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def adress_params
      params.require(:adress).permit(:title, :description, :location)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>Admin</h1>

app/views/adresses/_adress.html.erb
<div id="<%= dom_id adress %>" class="max-w-sm rounded overflow-hidden shadow-lg hover:bg-slate-100	p-4 my-4">
  <div class="flex items-center justify-center">
    <% if adress.image.present? %>
      <%= image_tag adress.image, class: "w-48 h-48 rounded" %>
    <% else %>
      <%= image_tag("no-image.jpg", width: 192) %>
    <% end %>
  </div>
  <p class="my-5">
    <strong class="block font-bold mb-1">Title:</strong>
    <span class="font-light text-slate-500">
      <%= adress.title %>
    </span>
  </p>

  <p class="my-5">
    <strong class="block font-bold mb-1">Description:</strong>
    <span class="font-light text-slate-500">
      <%= adress.description %>
    </span>
  </p>

  <p class="my-5">
    <strong class="block font-bold mb-1">Location:</strong>
    <span class="font-light text-slate-500">
      <%= adress.location %>
    </span>
  </p>

</div>

app/views/adresses/_form.html.erb
<%= form_with(model: adress, class: "contents") do |form| %>
  <% if adress.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(adress.errors.count, "error") %> prohibited this adress from being saved:</h2>

      <ul>
        <% adress.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :location %>
    <%= form.text_field :location, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/adresses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing adress</h1>

  <%= render "form", adress: @adress %>

  <%= link_to "Show this adress", @adress, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to adresses", adresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/adresses/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Adresses" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Adresses</h1>
    <%= link_to "New adress", new_adress_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="adresses" class="min-w-full border-2	rounded p-4 my-2 grid grid-rows-3 grid-flow-col gap-4">
    <% @adresses.each do |adress| %>
      <div>
        <%= render adress %>
        <p>
          <%= link_to "Show this adress", adress, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/adresses/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New adress</h1>

  <%= render "form", adress: @adress %>

  <%= link_to "Back to adresses", adresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/adresses/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @adress %>

    <%= link_to "Edit this adress", edit_adress_path(@adress), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
    <%= link_to "Back to adresses", adresses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this adress", @adress, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 font-medium" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchAddress</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>